{
 "title": "sample-dashboard",
 "description": "demo",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Raw logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"webapp\"} |= ``"
    }
   ]
  },
  {
   "title": "CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "flops" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 10 Slowest Endpoints (p95)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, (rate(prometheus_http_request_duration_seconds_bucket[5m]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(prometheus_http_response_size_bytes_count{job=\"prometheus\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}